server:
  servlet:
    context-path: /ai

spring:
  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key:
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B

